### ISSUE TITLE
Broken by Bethesda update?

### ISSUE THREAD

**Issue by Lamieur** [syncore/qclauncher#11]
Used to work even after the last QC patch, but suddenly broke yesterday. Now qclauncher.log says:

`{"level":"error","ts":"2018-06-11T20:08:06.572+0200","msg":"parse: build info response failed validation","error":"Build info response failed validation: no project info present","data":{"projects":[],"branches":[]}}
{"level":"error","ts":"2018-06-11T20:08:06.584+0200","msg":"send: error parsing remote response data","error":"Build info response failed validation: no project info present","data":"{\"branches\": [], \"projects\": []}"}
{"level":"error","ts":"2018-06-11T20:08:06.584+0200","msg":"getBuildInfo: error parsing build info response","error":"Build info response failed validation: no project info present","data":null}
{"level":"error","ts":"2018-06-11T20:08:06.584+0200","msg":"Launch: getBuildInfo error","error":"Build info response failed validation: no project info present","data":null}
{"level":"error","ts":"2018-06-11T20:08:06.584+0200","msg":"execMain: error occurred while executing the launch process.","error":"Build info response failed validation: no project info present"}
`

Judging by the errors I assumed it's just the update checker and tried running qclauncher -skipupdates, but that didn't help.

Bethesda.net Launcher still works, but that thing requires login every time and takes minutes to load, please save us again, syncore! :)

**Comment by Random1984** [comment]
Same problem here.
```{"level":"error","ts":"2018-06-12T13:25:51.514+0200","msg":"parse: build info response failed validation","error":"Build info response failed validation: no project info present","data":{"projects":[],"branches":[]}}
{"level":"error","ts":"2018-06-12T13:25:51.628+0200","msg":"send: error parsing remote response data","error":"Build info response failed validation: no project info present","data":"{\"branches\": [], \"projects\": []}"}
{"level":"error","ts":"2018-06-12T13:25:51.629+0200","msg":"getBuildInfo: error parsing build info response","error":"Build info response failed validation: no project info present","data":null}
{"level":"error","ts":"2018-06-12T13:25:51.629+0200","msg":"Launch: getBuildInfo error","error":"Build info response failed validation: no project info present","data":null}
{"level":"error","ts":"2018-06-12T13:25:51.629+0200","msg":"execMain: error occurred while executing the launch process.","error":"Build info response failed validation: no project info present"}´´´

**Comment by h13Bishop** [comment]
guys. there's no need in Bethesda launcher already. steam version is free for a week and will stay on your account after this period. don't bother the dev.

**Comment by Random1984** [comment]
I don't want to start a new account from 0.

**Comment by h13Bishop** [comment]
when I switched from Bethesda to steam there was no new account. it transferred somehow. that's for sure. still I don't remember how, maybe there was some "link account" procedure.
anyway there would be no harm if you try.

**Comment by Random1984** [comment]
I'm sorry but to change Bethesda launcher for Steam isn't a solution for me.

**Comment by Lamieur** [comment]
Steam takes even longer to log in than the Bethesda.net Launcher, so I'm not migrating any time soon :)

I just want my quick and light qclauncher, thank you very much :)

But thanks for mentioning the free offer, maybe I'll recruit some non-quaker friends, cheers!

**Comment by syncore** [comment]
Looks like things have changed -- I'll look into this shortly. Not making any promises

**Comment by syncore** [comment]
Download the [update](https://github.com/syncore/qclauncher/releases/tag/v1.04) and see if it works

**Comment by Lamieur** [comment]
Not surprisingly, it works :)

You're still a hero, here's an emoji :1st_place_medal:

**Comment by Random1984** [comment]
Runs like a charm. My respects, syncore.
