### ISSUE TITLE
1.04 broken by a QC update, 1.03 works again

### ISSUE THREAD

**Issue by Lamieur** [syncore/qclauncher#12]
Apparently to remove Red Shell, id/Bethesda reverted everything back to previous APIs, so qclauncher 1.04 spits:

```
{"level":"error","ts":"2018-06-26T21:15:11.574+0200","msg":"Launch: getBuildBranchIdentifiers error","error":"QC build/branch identifiers were not found"}
{"level":"error","ts":"2018-06-26T21:15:11.574+0200","msg":"execMain: error occurred while executing the launch process.","error":"QC build/branch identifiers were not found"}

```

But version 1.03 launches the game (after nagging me to update).

Just dropping this here for people looking for a work-around.

**Comment by Wa1tfor1t** [comment]
You are a gentleman and an outstanding community member Sir.

**Comment by syncore** [comment]
[v1.05](https://github.com/syncore/qclauncher/releases/tag/v1.05)

I've added back the old API behavior. If Bethesda decides to change it back, someone needs to alert me, as I can now specify whether the new API is to be used as a part of the launch process on my end, which should hopefully make things smoother in the future
