### ISSUE TITLE
Error on exec qclauncher 1.0.6

### ISSUE THREAD

**Issue by UladzimirTrehubenka** [syncore/qclauncher#16]
Looks like ExtractBNLauncherFP.exe cannot get FP, qclauncher.log content:
``
{"level":"error","ts":"2018-11-08T23:29:44.878+0300","msg":"extractFp: error occurred while running FP extraction tool","error":"exit status 3762504530"}
``

**Comment by syncore** [comment]
Is there a Windows Event Viewer entry for this error? If so, maybe look at that first.

Other things to consider:

- A minimum version of [.NET Framework 4.6.1](http://go.microsoft.com/fwlink/?linkid=671744) is required. [Version 4.7.2](https://www.microsoft.com/net/download/thank-you/net472) is the newest.

- The "Windows Management Instrumentation" service needs to be running.

**Comment by UladzimirTrehubenka** [comment]
Thanks a lot. After install [Version 4.7.2](https://www.microsoft.com/net/download/thank-you/net472) ExtractBNLauncherFP.exe works fine.
