### ISSUE TITLE
1501 is suddenly back for me.

### ISSUE THREAD

**Issue by lDavidl** [syncore/qclauncher#17]
At least it now gives me the option to put in my login info. Afterwards it loads fine. It would be awesome if it can be fixed anyways, it's getting annoying to do this every single time. Not sure if this even is a replicable issue and not just on my end, though.

**Comment by syncore** [comment]
I am experiencing no issues with this on my end. Have you recently updated your system and/or hardware configuration? 1501 is related to that. You might need to do the following:

1. Delete qclauncher's `data.qcl` file.
2. Open the Bethesda Launcher (and let it download BL updates, if necessary). 
3. Fully exit the Bethesda Launcher
4. Re-run [qclauncher 1.06](https://github.com/syncore/qclauncher/releases/download/v1.06/qclauncher-1.06.zip) - you will need to re-enter your login credentials and allow qclauncher to get the fingerprint from the Bethesda Launcher.
