### ISSUE TITLE
cant launch the game?

### ISSUE THREAD

**Issue by eatinsomewaffles** [syncore/qclauncher#7]
I choose my exe and enter my login etc and I get the error "An error occured while executing the launch process"   

This is what the log says?

{"level":"error","ts":"2017-08-23T11:50:03.345-0400","msg":"runQC: error starting QC","error":"fork/exec C:\\Program Files (x86)\\Bethesda.net Launcher\\games\\quakechampions\\client\\bin\\pc\\QuakeChampions.exe: The requested operation requires elevation."}
{"level":"error","ts":"2017-08-23T11:50:03.345-0400","msg":"func2: launch error","error":"fork/exec C:\\Program Files (x86)\\Bethesda.net Launcher\\games\\quakechampions\\client\\bin\\pc\\QuakeChampions.exe: The requested operation requires elevation."}

**Comment by syncore** [comment]
I haven't seen this issue yet - one suggested fix is available [here](https://stackoverflow.com/a/33755557) another is to right-click the executable and run as administrator. I have also heard that this may be the result of running from a symlinked directory. Let me know if any of these work

**Comment by eatinsomewaffles** [comment]
Hey sorry for the late reply,  I just tried and running as admin did fix it, thanks :]
