### ISSUE TITLE
Will there be a qlauncher for the steam version?

### ISSUE THREAD

**Issue by leonzin** [syncore/qclauncher#8]
I just want the function to limit the fps,
It's much better than nvidia profile inspector.

**Comment by syncore** [comment]
It is possible to use the same mechanism that QCLauncher uses to limit FPS on the Steam version. Go to your Quake Champions properties in Steam, click the `SET LAUNCH OPTIONS...` button and enter: ```--set /Config/CONFIG/maxFpsValue n``` replacing n with a number. As for a Steam version of QCLauncher, it should not be needed, however, I will continue to support the software for the considerable number of people who still play via Bethesda.


![fps_limit](https://user-images.githubusercontent.com/1934331/29646367-14d87058-8851-11e7-9cae-a092977246b2.png)

**Comment by leonzin** [comment]
thanks, man.
